# Generated by Django 4.2.11 on 2024-03-13 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('task_id', models.AutoField(primary_key=True, serialize=False)),
                ('task', models.CharField(max_length=255)),
                ('correct_answer', models.CharField(max_length=255)),
                ('is_completed', models.BooleanField()),
            ],
        ),
    ]
